import Head from 'next/head'
import styles from '../styles/Home.module.css'
import client from '../client'
import { WelcomeInformation } from '../model/welcome'

export default function Home({
  welcomeInformation,
}: {
  welcomeInformation: WelcomeInformation
}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bad Boi Eats</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{welcomeInformation.title}</h1>
        <p>{welcomeInformation.description}</p>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const welcomeInformation = await client.fetch(
    `*[_type == "welcomeInformation"][0]`
  )

  return {
    props: {
      welcomeInformation,
    },
  }
}
